#!/usr/bin/env python3
"""Export learned training data to a reusable Python seed module."""

import argparse
import statistics
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import select

from app.db.database import SessionLocal
from app.models.transaction import TrainingData


def build_seed_rows() -> list[tuple[str, str, float]]:
    grouped: dict[tuple[str, str], list[float]] = defaultdict(list)
    db = SessionLocal()
    try:
        rows = db.execute(
            select(TrainingData.description, TrainingData.corrected_label, TrainingData.amount)
            .where(TrainingData.description.is_not(None))
            .where(TrainingData.corrected_label.is_not(None))
            .where(TrainingData.amount.is_not(None))
        ).all()
    finally:
        db.close()

    for description, corrected_label, amount in rows:
        key = (description.strip(), corrected_label.strip())
        if key[0] and key[1]:
            grouped[key].append(float(amount))

    seed_rows: list[tuple[str, str, float]] = []
    for (description, corrected_label), amounts in sorted(grouped.items()):
        seed_rows.append((description, corrected_label, float(statistics.median(amounts))))
    return seed_rows


def write_seed_file(output_path: Path, rows: list[tuple[str, str, float]]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by generate_seed.py; do not edit by hand.",
        "",
        "USER_SEED_DATA: list[tuple[str, str, float]] = [",
    ]
    for description, label, amount in rows:
        lines.append(f"    ({description!r}, {label!r}, {amount!r}),")
    lines.append("]")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parent.parent / "app" / "constants" / "user_seed.py"),
    )
    args = parser.parse_args()

    rows = build_seed_rows()
    output_path = Path(args.output)
    write_seed_file(output_path, rows)
    print(f"Wrote {len(rows)} seed row(s) to {output_path}")


if __name__ == "__main__":
    main()