# Auto-generated by generate_seed.py; do not edit by hand.
# Source: finalized transactions only (category_final IS NOT NULL).
# Conflicts resolved by heuristics (amount thresholds, description patterns).
# Unresolvable conflicts excluded; see seed_conflicts.log.

USER_SEED_DATA: list[tuple[str, str, float]] = [
    ('BANKI ÁTVEZETÉS Kozpont', 'bank_fees', 0.0),
    ('DÍJ TERHELÉSE', 'bank_fees', -785.0),
    ('Hűségprogram jóváírás', 'bank_fees', 1222.0),
    ('Kozpont', 'bank_fees', -1607.5),
    ('Számlavezetés havi költsége', 'bank_fees', -600.0),

    ('D-Ugyfelkapu', 'bills', -21330.0),
    ('Digipay', 'bills', -6500.0),
    ('DMRV Zrt', 'bills', -7957.0),
    ('Elmuemasz.hu', 'bills', -8334.0),
    ('Elmuemaszenergiaszolga', 'bills', -8297.0),
    ('Hulladekgazdalkodas', 'bills', -3327.0),
    ('Icsekk', 'bills', -8741.0),
    ('Mvm Next', 'bills', -1372.0),
    ('Nkm Energia', 'bills', -11022.0),
    ('Vizcenter', 'bills', -6081.0),
    ('Vőlegény u. 2.', 'bills', -13970.0),
    ('Yettel.', 'bills', -4162.5),
    ('MOHU', 'bills', -4162.5),

    ('ATM', 'cash_withdrawal', -50000.0),

    ('Alpha Zoo', 'dogs', -4000.0),
    ('Fressnapf', 'dogs', -18798.0),
    ('kutyakajás.hu', 'dogs', -12853.5),
    ('Zooplus', 'dogs', -19040.0),

    ('Eleszto Bar', 'drink', -1680.0),

    ('?Tterem', 'eating_out', -2225.0),
    ('Belfrit', 'eating_out', -5000.0),
    ('Burger', 'eating_out', -1980.0),
    ('Burger King', 'eating_out', -4150.0),
    ('Cafe', 'eating_out', -2670.12),
    ('Coffe', 'eating_out', -3170.0),
    ('Delivery Hero', 'eating_out', -3680.0),
    ('E\'tterem', 'eating_out', -2225.0),
    ('Erzsébet Sörkert', 'eating_out', -3770.0),
    ('Etterem  Bufe', 'eating_out', -372.5),
    ('foodora', 'eating_out', -8089.0),
    ('Gyros', 'eating_out', -4000.0),
    ('HALPATKÓ', 'eating_out', -13950.0),
    ('Hamburgar', 'eating_out', -2228.16),
    ('IKEA BUDAORS ETTEREM', 'eating_out', -1750.0),
    ('IKEA SOROKSAR ETTERE', 'eating_out', -1700.0),
    ('KFC', 'eating_out', -1680.0),
    ('Ki\'nai Bu:fe\'', 'eating_out', -1080.0),
    ("Mcdonald's", 'eating_out', -5550.0),
    ('MILLENNIUMGARD', 'eating_out', -1900.0),
    ('Netpincer', 'eating_out', -4480.0),
    ('Pipi Food', 'eating_out', -3490.0),
    ('Pizza', 'eating_out', -2000.0),
    ('Restaurant', 'eating_out', -23024.3),
    ('Salatabar', 'eating_out', -1200.0),
    ('Wok Express', 'eating_out', -1190.0),
    ('Wolt', 'eating_out', -8019.0),

    ('Amznprime', 'entertainment', -3088.45),
    ('Gyógyfürdő', 'entertainment', -6300.0),
    ('MVM Dome', 'entertainment', 600.0),
    ('Ubisoft', 'entertainment', -2362.195),
    ('Állatpark', 'entertainment', -1010.0),

    ('Lukoil', 'fuel', -15619.0),
    ('Mol', 'fuel', -8199.0),
    ('Omv', 'fuel', -4353.0),
    ('Shell', 'fuel', -13339.0),
    ('To:lto"A\'ll', 'fuel', -20180.0),
    ('Toltoall', 'fuel', -14876.0),
    ('U:zemanyagto:lto', 'fuel', -20010.0),

    ('IKEA', 'furniture', -40462.5),
    ('IKEA', 'furniture', -70000.0),
    ('Ikea Bp Bev?s?rl? Utc', 'furniture', -14930.0),
    ('Ikea Budapest', 'furniture', -90045.0),
    ('IKEA SOROKSAR UGYFE', 'furniture', -34790.0),
    ('Jysk', 'furniture', -11390.0),
    ('JYSK', 'furniture', -24700.0),

    ('Exchanged to EUR', 'fx', -13690.0),
    ('Exchanged to HUF', 'fx', 967.08),

    ('Agroker', 'gardening', -45670.0),
    ('Kerte\'szet', 'gardening', -22840.0),

    ('Okmányiroda', 'general', -12600.0),

    ('Aldi', 'groceries', -4405.0),
    ('Auchan', 'groceries', -29420.0),
    ('Auchan', 'groceries', -31238.5),
    ('Cba', 'groceries', -1000.0),
    ('Cba E\'lelmiszer', 'groceries', -1000.0),
    ('Coop', 'groceries', -4595.32),
    ('Delikat', 'groceries', -11100.0),
    ('Kifli.hu', 'groceries', -23378.6),
    ('Konzum', 'groceries', -1685.51),
    ('Penny', 'groceries', -2000.0),
    ('Rea\'l', 'groceries', -2049.0),
    ('Simon Gyümölcs', 'groceries', -8585.0),
    ('SPAR', 'groceries', -5820.0),
    ('Tesco', 'groceries', -3488.0),

    ('Doha\'nybolt', 'habit', -2490.0),
    ('Dohanybolt', 'habit', -2204.5),

    ('Benu', 'health', -1599.0),
    ('Dentors Marina', 'health', -83500.0),
    ('Gyógyszertár', 'health', -4099.0),
    ('Patika', 'health', -3399.0),
    ('Rossmann', 'health', -5199.0),

    ('Biztosito', 'insurance', -46924.0),
    ('Kamat', 'interest', -6446.0),

    ('Babaaruhaz', 'kid', -6519.0),
    ('Dedoles', 'kid', -13340.0),
    ('LEVENDULA CIPOBOLT', 'kid', -30870.0),
    ('Kolorky', 'kid', -30000.0),

    ('Xlmoto', 'moto_gear', -31530.7),

    ('Parkol?S', 'parking', -564.0),

    ('Epuletgepeszet', 'renovation', -37342.0),
    ('Obi', 'renovation', -9293.0),
    ('Praktiker', 'renovation', -18239.2),

    ('IVANICS MOTOR', 'repair', -240067.0),
    ('Unix', 'repair', -21472.0),

    ('Morgan Stanley', 'salary', 1113750.0),

    ('80101797', 'saving_2', -50000.0),
    ('8152930-200', 'saving_2', -20150.0),

    ('Alipay', 'shopping', -8703.56),
    ('Alza', 'shopping', -34550.0),
    ('Amzn Mktp', 'shopping', -34550.0),
    ('Bauhaus.hu', 'shopping', -37990.0),
    ('Decathlon', 'shopping', -35390.0),
    ('Deichmann', 'shopping', -18980.0),
    ('Emag.hu', 'shopping', -22639.0),
    ('FOXPOST', 'shopping', -1699.0),
    ('H&M', 'shopping', -16492.0),
    ('Ipon Computer', 'shopping', -112278.0),
    ('Temu', 'shopping', -14571.0),

    ('Apple', 'subscriptions', -1923.85),

    ('Nav', 'tax', -29898.0),
    ('Nav Mobil', 'tax', -36280.0),
    ('Vámhivatal', 'tax', -2248000.0),

    ('Apple Pay top-up', 'topup', 2895.0),
    ('Revolut**', 'topup', -40000.0),

    ('PRÉMIUM ÖNKÉNTES', 'transfer', 77864.0),

    ('Bkk', 'transport', -350.0),
    ('Jegy.mav.hu', 'transport', -3239.0),
    ('MOL Limo', 'transport', -1715.0),
    ('MÁV', 'transport', -579.0),

    ('Autocesta', 'travel', -2162.11),
    ('Autoceste', 'travel', -1135.59),
    ('Blinkee', 'travel', -520.0),
    ('Bolt.eu', 'travel', -3730.0),
    ('Car', 'travel', -100000.0),
    ('Hotel', 'travel', -151171.0),
    ('Matrica', 'travel', -6749.0),
]
